apiVersion: v1
kind: Service
metadata:
  name: go-service
spec:
  selector:
    app: go-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080  # Expose it on this port on every node
  type: NodePort
