name: cicd-pipeline

on:
  push: 
    branches: [ main ]
    paths-ignore:
      - 'k8s/**'
      - 'README.md'
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.22.5'

      - name: Verify go version
        run: go version

      - name: Install Dependencies
        run: go mod tidy

      - name: Build
        run: go build -o my-app


      - name: Run Static Code Analysis
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=5m

      - name: Run Unit Tests
        run: go test -v ./...
    

  push:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: docker/setup-buildx-action@v1
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/jaychandra17/go-web-app:${{ github.run_number }}

  update-helm:
    runs-on: ubuntu-latest
    needs: push  # This job runs after the image is pushed

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}
          ref: main

      - name: Update Helm Values File
        run: |
          sed -i 's|tag: .*|tag: '"${{ github.run_number }}"'|' helm/go-web-app-chart/values.yaml

      - name: Commit and Push Changes
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git add helm/go-web-app-chart/values.yaml
          git commit -m "Update Helm chart with image tag ${{ github.run_number }}"
          git push